name: Format Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run format check
        run: python src/format_teams.py

      - name: Compare files
        run: |
          if ! diff -q data/teams.csv data/teams_formatted.csv; then
            echo "Format check failed. Please run 'python src/format_teams.py' to fix the formatting issues."
            exit 1
          else
            echo "Format check passed."
          fi
